CFLAGS=-Wall -g

all:  ex10

10:
	cc -Wall -g ex9.c -o 10

clean:
	# delete any file without extension except for Makefile and .gitignore
	ls | grep -v "\." | grep -E -v 'Makefile|.gitignore' |  xargs rm